# Generated by Django 2.0.2 on 2018-03-30 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducatorAccounts',
            new_name='EducatorAccount',
        ),
    ]
