# Generated by Django 2.0.2 on 2018-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0002_auto_20180330_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='final_grade',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
