# Generated by Django 2.0.2 on 2018-03-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0003_auto_20180330_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='name',
            field=models.CharField(default='ahmed', max_length=50),
            preserve_default=False,
        ),
    ]
