# Generated by Django 2.0.2 on 2018-04-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0005_educator_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Term'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Year'),
        ),
    ]
