# Generated by Django 2.0.2 on 2018-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0006_auto_20180402_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Adam', max_length=50),
            preserve_default=False,
        ),
    ]
