# Generated by Django 2.0.2 on 2018-04-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0007_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='is_anonymous',
            field=models.BinaryField(),
        ),
    ]
