# Generated by Django 2.0.2 on 2018-04-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0008_auto_20180404_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
