# Generated by Django 2.0.2 on 2018-04-05 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0010_studentcourse_prediction_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
