# Generated by Django 2.0.2 on 2018-04-06 12:29

from django.db import migrations, models

import dashboard.models.utilities


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0013_auto_20180406_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.ImageField(upload_to=dashboard.models.utilities.get_path_with_time_now),
        ),
    ]
