# Generated by Django 2.0.2 on 2018-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0014_auto_20180406_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatoraccount',
            name='url',
            field=models.URLField(),
        ),
    ]
