# Generated by Django 2.0.2 on 2018-04-06 12:57

from django.db import migrations, models

import dashboard.models.utilities


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0015_auto_20180406_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='image_url',
        ),
        migrations.AddField(
            model_name='educator',
            name='photo',
            field=models.ImageField(default='hhh', upload_to=dashboard.models.utilities.get_path_with_time_now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educator',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
