# Generated by Django 2.0.2 on 2018-04-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0018_auto_20180406_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='family_relation_quality',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_education',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='free_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='go_out_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='health_status',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_education',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='travel_time',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
