# Generated by Django 2.0.2 on 2018-04-12 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0020_auto_20180406_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='gender',
        ),
    ]
