# Generated by Django 2.0.2 on 2018-04-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0021_auto_20180412_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreview',
            name='student_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Year'),
            preserve_default=False,
        ),
    ]
