# Generated by Django 2.0.4 on 2018-04-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0022_studentreview_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
