# Generated by Django 2.0.4 on 2018-04-25 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0025_auto_20180424_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3),
                                                               django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='family_relation_quality',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_education',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'No Education'), (1, 'Primary Education'), (2, 'Preparatory Education'),
                         (3, 'Secondary Education'), (4, 'Higher Education')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='free_time',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='go_out_time',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='health_status',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_education',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'No Education'), (1, 'Primary Education'), (2, 'Preparatory Education'),
                         (3, 'Secondary Education'), (4, 'Higher Education')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='travel_time',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Less than 15 min'), (2, 'From 15 to 30 min'), (3, 'From 30 min to 1 hour'),
                         (4, '1 hour')]),
        ),
    ]
