# Generated by Django 2.0.4 on 2018-04-26 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0028_auto_20180426_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='failures',
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
