# Generated by Django 2.0.4 on 2018-05-01 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('dashboard', '0029_auto_20180426_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('group',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='auth.Group')),
                ('url_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='studentreview',
            name='student_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Year'),
        ),
    ]
